import { SparklesIcon } from '@heroicons/react/20/solid'
import React from 'react'

import { Text } from '../ui/text'

export default function Build({ profile }) {
  const { build } = profile

  if (!build) return null

  return (
    <div className="flex flex-col gap-2 mt-8 p-4 border border-gray-200 rounded-md">
      <div className="flex items-center gap-2">
        <SparklesIcon className="size-5 text-yellow-600" />
        <Text className="font-medium">Built by your AI Career Coach</Text>
      </div>
      <Text>
        This information was generated by your <i>AI Career Coach Assistant</i>{' '}
        and will be used to help you find your next job.
      </Text>
    </div>
  )
}
